apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  labels:
    app: course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: sit722acrrithwik5566.azurecr.io/course-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: course-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: course_db
            - name: JWT_SECRET
              value: mysecretkey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-db
  labels:
    app: course-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-db
  template:
    metadata:
      labels:
        app: course-db
    spec:
      containers:
        - name: course-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: course_db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sit722acrrithwik5566.azurecr.io/frontend:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config